mapbox/dash-android-examples

.gitignore
app/build.gradle.kts
app/src/main/java/com/mapbox/dash/example/CommonExt.kt
app/src/main/java/com/mapbox/dash/example/CustomLocationPuck.kt
app/src/main/java/com/mapbox/dash/example/HeadlessModeFragment.kt
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/MainApplication.kt
app/src/main/java/com/mapbox/dash/example/MapGptViewModel.kt
app/src/main/java/com/mapbox/dash/example/ThemeViewModel.kt
app/src/main/res/layout/fragment_headless_mode.xml
app/src/main/res/layout/item_spinner.xml
app/src/main/res/layout/layout_customization_menu.xml

Add example of using Dash SDK in headless mode
Add example of location puck customization
Add mapgpt enabling/disabling
Add route preferences configuration

Upgrade Dash SDK example to v1.0.0-beta.10

---

app/src/main/java/com/mapbox/dash/example/DrawerActivity.kt
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/ThemeViewModel.kt
app/src/main/res/layout/layout_customization_menu.xml

https://mapbox.atlassian.net/browse/NAVAND-3269
https://mapbox.atlassian.net/browse/NAVAND-3270

add examples of configuring paddings and sidebars

---

app/src/main/java/com/mapbox/dash/example/MainApplication.kt

1. Enable Bug button via Configuration API:
```
debugSettings {
// To show Bug Button in UI
showSendDebugInfoButton = true
// To show option in the setting to disable/enable Bug Button
showDisplaySendDebugInfoButtonOption = true
}
```
3. As the **issue is noticed tap ASAP** the **Bug button**. It will save a debug bundle zip on the file system at this absolute path:
`/data/user/<user_id>/<your_app_package_name>/files/debug_bundle.zip`
5. Pull the bundle zip via `adb pull` command. (P.S. this might be a tricky moment for a regular android devices, and some additional commands to grant additional rights for the user might be needed)
4. Send the text description (steps to reproduce and conditions) of the issue to the Mapbox team and attach a debug bundle zip. …

Enable Bug Button

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml

[Screen_recording_20240802_162423.webm](https://github.com/user-attachments/assets/49b87246-8956-45d5-933b-25970c05c1d1)

add card header configuration example

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt

Looks like changing density is not required and we are fine with UI becoming bigger. This lets us simplify the hack
https://github.com/user-attachments/assets/ad9bc145-34e6-4a8d-9f97-a810ca6c31ec

simplify layout toggle hack

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt

[Screen_recording_20240815_171141.webm](https://github.com/user-attachments/assets/ff87263f-c9c1-48fb-91bf-7aa08b65fe73)

add routes button example

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml
app/src/main/res/values/strings.xml

https://github.com/user-attachments/assets/972f823a-090f-4440-a91c-9c1f113fc538

add option to override density

---

app/build.gradle.kts
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/SamplePlacesViewComposer.kt
app/src/main/java/com/mapbox/dash/example/ShowcaseSearchEngine.kt
app/src/main/java/com/mapbox/dash/example/ShowcaseSearchResultsAdapter.kt

- **Added `pinCoordinate` property to `DashSearchResult`:** `pinCoordinate` refers to the coordinate of the POI, while `coordinate` refers to a routable point to the POI.
- **Added `modifier` to `PlacesPreviewUiComposer`:** The `modifier` now includes information about sizes, enabling customization of the UI in the places preview by allowing control over the layout dimensions and appearance.

 - Migration to beta35

---

app/src/main/java/com/mapbox/dash/example/ui/SampleDestinationPreview.kt

 Add samples with new props in DestinationPreviewUiState

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/dash/example/service/UXFBackgroundService.kt
app/src/main/java/com/mapbox/dash/example/service/UXFBackgroundServiceAction.kt
app/src/main/java/com/mapbox/dash/example/service/UXFBackgroundServiceLauncherActivity.kt
app/src/main/java/com/mapbox/dash/example/service/UXFBackgroundState.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml-v25/shortcuts.xml

https://github.com/user-attachments/assets/0144be23-d7c7-4a65-a2eb-87e4130a54d8

NAVAND-3708: Add an example of using UXF Headless mode inside an Android Service component

---

app/src/main/java/com/mapbox/dash/example/MainApplication.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleDriverNotificationView.kt

[border_crossing_example.webm](https://github.com/user-attachments/assets/e4bdbeed-58fe-403b-ab07-ba01bce3a875)
[slow_traffic_example.webm](https://github.com/user-attachments/assets/70b6dfe0-8ab2-4162-93f4-9d97f85ce994)

Sample for the border crossing & slow traffic driver notifications

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/relaxedmode/RelaxedModeActivity.kt
app/src/main/res/drawable/baseline_remove_red_eye_24.xml
app/src/main/res/layout/activity_relaxed_mode.xml
app/src/main/res/values/themes.xml

https://github.com/user-attachments/assets/2d51878f-e759-4910-b5cb-3dc73d135bf2

NAVAND-3557: Verify the ability to set static image instead of map

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/showcase/app/ui/custom/edittrip/DragDropState.kt
app/src/main/java/com/mapbox/dash/showcase/app/ui/custom/edittrip/DragDropStateExt.kt
app/src/main/java/com/mapbox/dash/showcase/app/ui/custom/edittrip/SampleEditTrip.kt
app/src/main/res/layout/activity_relaxed_mode.xml
app/src/main/res/layout/layout_customization_menu.xml

https://github.com/user-attachments/assets/b8baff21-6def-44ec-bc9f-d87e03a85623

Added sample how to customize Edit trip card

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/dash/example/service/UXFBackgroundService.kt
app/src/main/java/com/mapbox/dash/example/service/UXFBackgroundServiceLauncherActivity.kt

https://github.com/user-attachments/assets/61b29b8e-1dea-47bd-84d2-57a1d00341fb
https://github.com/user-attachments/assets/4588232a-3dbd-4ff6-88ec-de5650ef7401
https://github.com/user-attachments/assets/69db327e-7b82-4be7-ba78-fc961875f642

Fix request permissions when showcase app installed, but zero permission granted to start service

---

app/src/main/res/values-sw600dp/dimens.xml

add example of configuring street name size and paddings

---

app/src/main/java/com/mapbox/dash/example/ui/SampleDriverNotificationView.kt

[speed_camera_notificatin.webm](https://github.com/user-attachments/assets/3052fa68-de05-4460-a481-691886c5868e)

Speed cameras sample

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml
app/src/main/res/values/strings.xml
gradle.properties

[Screen_recording_20241023_135520.webm](https://github.com/user-attachments/assets/c8000c3b-c285-4929-bf98-51d70bd6a568)

add external profile sample

---

app/build.gradle.kts
app/src/CustomCluster/AndroidManifest.xml
app/src/CustomCluster/java/com/mapbox/dash/showcase/app/ShowcaseClusterActivity.kt
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/MainApplication.kt

add default and custom cluster activity examples

---

app/src/main/java/com/mapbox/dash/example/MainApplication.kt

https://github.com/user-attachments/assets/fa37f27e-42ca-4045-84f2-831e4ca04f68

Add default EV data provider

---

app/src/main/java/com/mapbox/dash/example/MainApplication.kt

Added 3d camera state for FreeDrive

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml

https://github.com/user-attachments/assets/7fd2d35c-bc5e-44f7-b21b-8b8448d4a6ce

Added debug option to update pitch in FreeDrive

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleOfflineRouteAlert.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleSearchPanel.kt
app/src/main/res/drawable/ic_alert_close.xml
app/src/main/res/layout/layout_customization_menu.xml

[Screen_recording_20241114_165402.webm](https://github.com/user-attachments/assets/c736d3d5-29a0-4135-bc2d-71bc903c61c9)

add custom offline alert example

---

app/build.gradle.kts
app/src/main/java/com/mapbox/dash/example/MainActivity.kt

Add an example of how to observe Debug Bundle is ready when a user taps the Bug Button

Migrate to Beta.42.2

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/MainApplication.kt
app/src/main/java/com/mapbox/dash/example/ShowcaseSearchResultsAdapter.kt
app/src/main/java/com/mapbox/dash/example/ui/DragDropState.kt
app/src/main/java/com/mapbox/dash/example/ui/DragDropStateExt.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleEditTrip.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleEtaView.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleTripSummaryView.kt

I did the same in our internal repository, copying the changes here for consistency

remove app theme usages from sample trip summary view

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleResumeGuidanceView.kt
app/src/main/res/layout/layout_customization_menu.xml

[Screen_recording_20250115_145300.webm](https://github.com/user-attachments/assets/6bf469ad-0005-4b2d-89ed-f238b20b1b4c)

add custom resume guidance view example

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml

[Screen_recording_20250109_121313.webm](https://github.com/user-attachments/assets/493e80ed-f244-4465-a6a8-f043f6232180)

add upcoming lane guidance example

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleUpcomingManeuversBanner.kt
app/src/main/res/layout/layout_customization_menu.xml

Observe waypoints and custom upcoming maneuvers examples

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/WeatherLayer.kt
app/src/main/java/com/mapbox/dash/example/WeatherViewModel.kt
app/src/main/res/layout/layout_customization_menu.xml

https://github.com/user-attachments/assets/323ca94a-fecc-4a9a-ac90-f58f8784f17d

Add example of usage getWarningAlongRoute method

---

app/src/main/java/com/mapbox/dash/example/MainApplication.kt

[Compose code sample](https://github.com/mapbox/dash-android-examples/blob/main/app/src/main/java/com/mapbox/dash/example/ui/SampleDriverNotificationView.kt#L207) for better ev route notification was added previously
https://github.com/user-attachments/assets/291adc08-8cf9-4dc7-82e8-2015100fb669
https://github.com/user-attachments/assets/27def8b5-dbb4-401b-a102-d4bbbcfee68a

Ev trip monitoring notifications

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml

https://github.com/user-attachments/assets/94d1a3b8-2d35-4e1d-a1b0-35f72b3c3baf

Add EV range map api example

---

app/src/main/java/com/mapbox/dash/example/MainApplication.kt

new tiles are bigger than 30.Gb

Increase disk quota

---

app/src/main/java/com/mapbox/dash/example/DestinationWeatherForecast.kt
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/WeatherViewModel.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleEtaView.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleTripOverviewItemsView.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleTripSummaryView.kt

https://github.com/user-attachments/assets/6d2b151d-41af-49b3-8415-824e860a089c

Extend example of weather to show condition at arrival time

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/WeatherViewModel.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleDestinationPreview.kt

https://github.com/user-attachments/assets/00c43432-d5f8-4d8d-a2a1-9bd48a50e48a

Extend example of current weather condition

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/res/layout/layout_customization_menu.xml

 - Added example to reset navigation state

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt

https://github.com/user-attachments/assets/663d2bcf-d4ed-41e0-a381-abd296041fb3

Add range map frame points as additional points to frame camera

---

app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleRouteCalloutView.kt
app/src/main/res/layout/layout_customization_menu.xml

https://github.com/user-attachments/assets/af3b19b5-8187-4eea-9672-c54d274998f9

Add custom callout sample

---

app/build.gradle.kts
app/src/main/java/com/mapbox/dash/example/MainActivity.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleSearchArea.kt
app/src/main/java/com/mapbox/dash/example/ui/SampleStreetName.kt
app/src/main/res/layout/layout_customization_menu.xml

add compose examples of customizing search this area button and street name label

Bumb uxf to 1.1.0-rc.1
